version '3.1'

services:
    postgresdb:
            image: postgres
            restart: always
            environment:
                POSTGRES_USER: admin
                POSTGRES_PASSWORD: batata
                POSTGRES_DB: morphussell
            ports:
                    - 5432:5432
    mpbackend:
            build:
                    context: ./back/src/MSell.CRUDs.API/
                    dockerfile: ./dotnet
            depends_on:
                    - postgresdb
    mpfrontend:
            build:
                    context: ./front/src/
                    dockerfile: ./next-node
            ports:
                    - 80:3000
            restart: always
            depends_on:
                    - mpbackend
    reverse_proxy:
            build:
                    context: .
                    dockerfile: .nginx
            ports:
                    - 80:8080
            restart: always
            depends_on:
                    - mpfrontend
